"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { usePathname, useRouter } from "next/navigation";
import { Check, LoaderCircle, SlidersHorizontal } from "lucide-react";
import clsx from "clsx";
import type { Category } from "@/types";

type Filters = { q: string; category: string; min: string; max: string; sort: string };
type FilterBarProps = { categories: Category[]; defaults: Partial<Filters>; resultCount: number; suggestions: unknown[]; maxBudget: number };
const empty: Filters = { q: "", category: "all", min: "", max: "", sort: "featured" };

export function FilterBar({ categories, defaults, resultCount, maxBudget }: FilterBarProps) {
  const router = useRouter(); const pathname = usePathname(); const [filters, setFilters] = useState<Filters>({ ...empty, ...defaults }); const [pending, startTransition] = useTransition(); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const selectedBudget = filters.max ? Number(filters.max) : maxBudget;
  useEffect(() => { const restore = () => { if (timer.current) clearTimeout(timer.current); const params = new URLSearchParams(window.location.search); setFilters(Object.fromEntries(Object.entries(empty).map(([key, value]) => [key, params.get(key) ?? value])) as Filters); }; window.addEventListener("popstate", restore); return () => { if (timer.current) clearTimeout(timer.current); window.removeEventListener("popstate", restore); }; }, []);
  function update(next: Filters, delay = 0) { setFilters(next); if (timer.current) clearTimeout(timer.current); const navigate = () => { const params = new URLSearchParams(); Object.entries(next).forEach(([key, value]) => { if (value && value !== empty[key as keyof Filters]) params.set(key, value); }); startTransition(() => router.replace(`${pathname}${params.size ? `?${params}` : ""}`, { scroll: false })); }; if (delay) timer.current = setTimeout(navigate, delay); else navigate(); }
  return <section aria-label="Product filters" className="rounded-2xl border border-slate-200/80 bg-white/95 p-3 shadow-[0_16px_38px_rgba(15,23,42,0.10)] backdrop-blur sm:p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap items-center gap-2"><span className="mr-1 inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400"><SlidersHorizontal size={13} /> Collections</span>{[{ id: "all", name: "All" }, ...categories].map((category) => <button key={category.id} type="button" aria-pressed={filters.category === category.id} onClick={() => update({ ...filters, category: category.id })} className={clsx("inline-flex min-h-9 items-center gap-1.5 rounded-full border px-3.5 text-sm font-semibold transition", filters.category === category.id ? "border-emerald-700 bg-emerald-700 text-white shadow-sm" : "border-slate-200 bg-white text-slate-600 hover:border-emerald-300 hover:text-emerald-800")}><Check size={13} aria-hidden="true" className={filters.category === category.id ? "block" : "hidden"} />{category.name}</button>)}<button type="button" aria-pressed={filters.min === "" && filters.max === "50"} onClick={() => update(filters.min === "" && filters.max === "50" ? { ...filters, max: "" } : { ...filters, min: "", max: "50" })} className={clsx("min-h-9 rounded-full border px-3.5 text-sm font-semibold transition", filters.min === "" && filters.max === "50" ? "border-[#e76f51] bg-[#e76f51] text-white shadow-sm" : "border-[#e76f51]/25 bg-[#fff3ed] text-[#b84f34] hover:border-[#e76f51]")}>Under $50</button></div><div className="flex min-w-0 items-center gap-3 rounded-xl bg-slate-50 px-3 py-2 sm:min-w-80"><div className="min-w-20"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Budget</p><p className="text-sm font-bold text-[#172033]">{selectedBudget >= maxBudget ? "Any budget" : `Up to $${selectedBudget}`}</p></div><input aria-label="Maximum budget" type="range" min="0" max={maxBudget} step="10" value={selectedBudget} onChange={(event) => { const value = Number(event.target.value); update({ ...filters, min: "", max: value >= maxBudget ? "" : String(value) }, 250); }} className="h-2 min-w-0 flex-1 cursor-pointer accent-[#ef8354]"/><span role="status" className="text-xs font-semibold text-slate-500">{pending ? <LoaderCircle size={15} className="animate-spin" /> : `${resultCount} items`}</span></div></div></section>;
}
