"use client";
import { useState, type FormEvent } from "react";
import { Star } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import type { ProductReview } from "@/types";

export function ProductReviews({ productId, initialReviews }: { productId: string; initialReviews: ProductReview[] }) {
  const [reviews, setReviews] = useState(initialReviews); const [rating, setRating] = useState(5); const [comment, setComment] = useState(""); const [error, setError] = useState(""); const [sending, setSending] = useState(false); const router = useRouter(); const pathname = usePathname();
  const average = reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSending(true); setError(""); const response = await fetch(`/api/products/${productId}/reviews`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating, comment }) }); if (response.status === 401) { router.push(`/login?next=${encodeURIComponent(pathname)}`); return; } const payload = await response.json(); if (!response.ok) setError(payload.error ?? "Could not add your review."); else { setReviews((items) => [payload.data, ...items]); setComment(""); } setSending(false); }
  return <section className="mx-auto max-w-[1500px] border-t border-slate-200 px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-sm font-semibold uppercase text-emerald-700">Customer reviews</p><div className="mt-4 flex items-end gap-3"><strong className="text-5xl text-[#172033]">{average.toFixed(1)}</strong><span className="pb-1 text-sm text-slate-500">out of 5</span></div><div className="mt-3 flex items-center gap-1 text-[#d65f3f]">{[1,2,3,4,5].map((value)=><Star key={value} size={18} fill={value <= Math.round(average) ? "currentColor" : "none"}/>)}</div><p className="mt-3 text-sm text-slate-500">{reviews.length} {reviews.length === 1 ? "review" : "reviews"} for this product</p><form onSubmit={submit} className="mt-7 space-y-3 rounded-xl bg-slate-50 p-4"><p className="font-semibold text-[#172033]">Share your experience</p><div className="flex gap-1">{[1,2,3,4,5].map((value)=><button key={value} type="button" onClick={()=>setRating(value)} aria-label={`${value} stars`} className="text-[#d65f3f]"><Star size={20} fill={value<=rating?"currentColor":"none"}/></button>)}</div><textarea value={comment} onChange={(event)=>setComment(event.target.value)} minLength={10} maxLength={800} required placeholder="What did you think of this product?" className="min-h-24 w-full rounded-md border border-slate-200 bg-white p-3 text-sm outline-none focus:border-emerald-700"/><button disabled={sending} className="rounded-md bg-[#172033] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{sending ? "Posting..." : "Post review"}</button>{error?<p role="alert" className="text-sm text-red-600">{error}</p>:null}</form></div><div className="space-y-4">{reviews.length ? reviews.map((review)=><article key={review.id} className="rounded-xl border border-slate-200 p-5"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[#172033]">{review.authorName}</p><span className="flex text-[#d65f3f]">{[1,2,3,4,5].map((value)=><Star key={value} size={14} fill={value<=review.rating?"currentColor":"none"}/>)}</span></div><p className="mt-3 leading-7 text-slate-600">{review.comment}</p><p className="mt-3 text-xs text-slate-400">{new Intl.DateTimeFormat("en", { month:"long", day:"numeric", year:"numeric" }).format(new Date(review.createdAt))}</p></article>):<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No reviews yet. Be the first to share your experience.</div>}</div></div></section>;
}
